### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by ollynevard** [odarriba/asdf-php#10]
Does it make sense to add support for composer to this plugin? And also support for default global packages as per the nodejs and ruby plugins?

If you think this is worthwhile doing and are open to a PR, I'll have a stab at implementing it.

**Comment by j-dexx** [comment]
Isn't npm part of node though?  Gems are included in ruby and I think they are including the equivalent package (bundler) in core ruby.

Just pointing out it's a slightly different scenario.

**Comment by salzig** [comment]
@j-dexx only gems is included, not bundler. :)

**Comment by j-dexx** [comment]
@salzig I did say including :)...[it was added as a default gem in ruby 2.6](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/)

> Bundler is now installed as a default gem.

**Comment by salzig** [comment]
@j-dexx nice, didn't realized that :)

**Comment by AdsonCicilioti** [comment]
Expose composer vendors binaries, please!
