### ISSUE TITLE
Use `make -j $(nproc)` to speed php build

### ISSUE THREAD

**Issue by liaoya** [odarriba/asdf-php#11]
Is it possible call `make -j $(nproc)` in install script to speed php build to make good use of multi-cores,

This will save a lot of time.

**Comment by Rican7** [comment]
Hmm... I just got here after a painfullllly slow build process on a 8-core/16-thread machine.

I did some research and found:

 - asdf-vm/asdf#57
 - asdf-vm/asdf#75
 - asdf-vm/asdf#147

On it...
