### ISSUE TITLE
Add support for argon2

### ISSUE THREAD

**Issue by williamokano** [odarriba/asdf-php#19]
When compiling PHP, you can enable the argon2 hashing algorithm by passing the `--with-password-argon2` into the configure step.

Also argon2 needs some additional libraries, such as `argon2 libargon2-0 libargon2-0-dev` (ubuntu based).

Argon2 stuff can be found here on this zend fw post https://framework.zend.com/blog/2017-08-17-php72-argon2-hash-password.html

**Comment by ramsey** [comment]
I'm curious why this was closed as completed. asdf-php doesn't appear to have support for `--with-password-argon2` yet, unless I'm missing something.

Would the maintainers be open to a PR for this functionality?
